name: Test Build

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      run: |
        docker build . --file Dockerfile --tag dnbresuse-test:$(date +%s
    - name: Remove Image
      run: |
        docker image rm dnbresuse-test:$(date +%s